### ISSUE TITLE
Error updating adresses

### ISSUE THREAD

**Issue by nnikif** [Accelo/docs#9]
I make a put request according to the documentation in order to update address:
PUT /addresses/{address_id}
I get a 400 message "Failed to locate address with # 1", even though the address id is legitimate, the get request with the same URL works perfectly.

**Comment by matthewhughes112** [comment]
Hello,

Thanks for bringing this to our attention. This looks like a bug, I'll look to get a fix out ASAP.

As a reminder, you can also share issues on our [Developer Forum](https://groups.google.com/forum/#!forum/accelo-devs)

**Comment by KurtWagner** [comment]
Thanks for sharing. The problem has been fixed. Next time, please use the [developer forum](https://groups.google.com/forum/#!forum/accelo-devs) to share any issues you're having. This repo is just for the documentation.
